ElementSizeIndicator #351
idaholab/mastodon pull request #357
Opened 2021-01-04 18:04 UTC by somu15

## Reason
Currently, the shear wave velocity indicator in MASTODON is restricted to soil simulations. A generic indicator would permit the user to input any desired material property as an indicator for the minimum element size marker. 

## Design
GenericMaterialIndicator class will be created to permit any material property the user desires to be the indicator for the minimum element size. 

## Impact
Among having other applications, this indicator class will permit fluid-structure interaction simulations where the fluid can have a significantly coarser mesh than the structure. Overall, this indicator may reduce the computational costs while preserving variable/auxvariable accuracies in the structural domain.

closes #351

2021-01-04 18:08 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/653406/) on 43a1ee5 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/mastodon/docs/PRs/357/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/mastodon/docs/PRs/357/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 97df8563d9a3ff880a06881e108943116a8d2382`

2021-01-04 18:11 UTC, somu15 commented
@cbolisetti Per our discussion, I created an element_size_indicator class that will assign the element size for the block given as a MaterialProperty. Please let me know if you have suggestions.

2021-01-04 21:00 UTC, moosebuild commented
Job [Test](https://civet.inl.gov/job/653409/) on 5f64ddb wanted to post the following:

View the site [here](https://mooseframework.inl.gov/mastodon/docs/PRs/357/site)

This comment will be updated on new commits.

2021-01-04 21:23 UTC, cbolisetti requested changes

2021-01-04 21:23 UTC, cbolisetti commented on doc/content/source/indicators/ElementSizeIndicator.md
> +equals the given `element_size`.
This text implies that the indicator enforces the mesh size automatically, which they don't. This indicator just calculates the element size from a material property. Also the mesh size is not adapted to be equal to the `element_size`. The minimum element size marker, when used, will keep refining until the min element size is reached. 

Please change this text accordingly.

2021-01-04 21:23 UTC, cbolisetti commented on doc/content/source/indicators/ElementSizeIndicator.md
> +the mesh element size to be equal to the `element_size`. Enough number of `initial_steps`
Does the MaterialPropertyName have to be element_size? From the code, it looks like it can be anything.

2021-01-04 21:23 UTC, cbolisetti commented on src/indicators/ElementSizeIndicator.C
> +      "The value of the material that will control the mesh refinement.");
This is the name of the property, and not the value. Please change the description. 

Also, make this a RequiredParam and remove the default.

2021-01-04 21:23 UTC, cbolisetti commented on src/indicators/ElementSizeIndicator.C
> +    _element_size(getMaterialProperty<Real>("element_size")),
Why input the material property name if you are directly getting the property with the name "element_size"? 

this line should be 
`_element_size(getMaterialProperty<Real>(getParam<MaterialPropertyName>("element_size"))),`

2021-01-04 21:24 UTC, cbolisetti commented
> @cbolisetti Per our discussion, I created an element_size_indicator class that will assign the element size for the block given as a MaterialProperty. Please let me know if you have suggestions.

@somu15 looks fine, needs a few minor changes.

2021-01-04 21:30 UTC, somu15 commented
> > @cbolisetti Per our discussion, I created an element_size_indicator class that will assign the element size for the block given as a MaterialProperty. Please let me know if you have suggestions.
> 
> @somu15 looks fine, needs a few minor changes. It looks like the shearwaveindicator page has some errors in the equation rendering. Can you fix that in this PR too?

Thanks for your comments. Yes, I will fix the shearwaveindicator page.

2021-01-18 19:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/661477/) on 82119e9 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/mastodon/docs/PRs/357/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/mastodon/docs/PRs/357/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 97df8563d9a3ff880a06881e108943116a8d2382`

2021-01-18 19:12 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/661479/) on 869b8e1 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/mastodon/docs/PRs/357/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/mastodon/docs/PRs/357/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 97df8563d9a3ff880a06881e108943116a8d2382`

2021-01-18 19:18 UTC, somu15 commented
@cbolisetti Per our discussion, I have generalized the minimumelementsizemarker class to accept an element size value. Right now, both the element_size and indicator params are optional and have to default to some value if the user does not provide any. So, in the doc, I have made an alert note stating that if both indicator and element_size are provided, indicator will control the mesh refinement. If neither are provided, the element_size will default to one and it will control. Let me know of suggestions.

2021-01-18 19:23 UTC, cbolisetti commented
> @cbolisetti Per our discussion, I have generalized the minimumelementsizemarker class to accept an element size value. Right now, both the element_size and indicator params are optional and have to default to some value if the user does not provide any. So, in the doc, I have made an alert note stating that if both indicator and element_size are provided, indicator will control the mesh refinement. If neither are provided, the element_size will default to one and it will control. Let me know of suggestions.

How about throwing an error if both or none are provided? Enforce that only one is provided.

2021-01-18 19:29 UTC, somu15 commented
> > @cbolisetti Per our discussion, I have generalized the minimumelementsizemarker class to accept an element size value. Right now, both the element_size and indicator params are optional and have to default to some value if the user does not provide any. So, in the doc, I have made an alert note stating that if both indicator and element_size are provided, indicator will control the mesh refinement. If neither are provided, the element_size will default to one and it will control. Let me know of suggestions.
> 
> How about throwing an error if both or none are provided? Enforce that only one is provided.

Both indicator and element_size will default to some value if not provided. So, if I create a mooseerror in the constructor then it gets called every time. Even if the user did not specify an element value.

2021-01-20 21:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/664815/) on ede1c70 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/mastodon/docs/PRs/357/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/mastodon/docs/PRs/357/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 97df8563d9a3ff880a06881e108943116a8d2382`

2021-01-21 17:02 UTC, cbolisetti requested changes
Looks pretty good. Please also add a test for indicator input.

2021-01-21 17:02 UTC, cbolisetti commented on test/tests/markers/minimum_element_size/minimum_element_size_value.i
> +[Mesh]
Can you remove the dots from the input file? Those are outdated and we should stop using them. We just need the square brackets now.

2021-01-25 18:24 UTC, somu15 commented
@cbolisetti I made changes based on your comments. Please let me know if further changes are required.

2021-01-25 22:12 UTC, cbolisetti commented on doc/content/source/markers/MinimumElementSizeMarker.md
> +via the "indicator" parameter or an "element_size" value. If an element has a minimum length greater than the minimum element defined by either the Indicator or the Element Size, then the element is
Please proofread this again.

2021-01-27 23:42 UTC, cbolisetti commented on doc/content/source/markers/MinimumElementSizeMarker.md
> +via the "indicator" parameter or an "element_size" value. If an element has a minimum length greater than the minimum element defined by either the Indicator or the Element Size, then the element is
If an element has a minimum dimension greater than the size defined by either the Indicator or the `element_size` input parameter, then the element is marked for refinement,

2021-02-03 00:10 UTC, moosebuild commented
Job [Test](https://civet.inl.gov/job/669304/) on b8a8a87 : invalidated by @cbolisetti

Re-running for website.

2021-02-03 04:55 UTC, moosebuild commented
Job [Test](https://civet.inl.gov/job/669304/) on b8a8a87 : invalidated by @cbolisetti

re-running.

2021-02-03 04:57 UTC, cbolisetti approved these changes
Looks fine now. Looks like one of the tests is failing because of a timeout. Can you shorten it and push a commit?

2021-02-03 23:09 UTC, cbolisetti approved these changes

2021-02-03 23:09 UTC, merged