Code and tests #358
idaholab/mastodon pull request #362
Opened 2021-01-20 22:06 UTC by somu15

## Reason
To compute the moment about a point given the stress tensor and the required direction.

## Design
SidesetMoment postprocessor class will be implemented.

## Impact
No impact on existing classes.

closes #358

2021-01-20 22:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/664941/) on 35db52d wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/mastodon/docs/PRs/362/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/mastodon/docs/PRs/362/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 4d9e6a53739a071f7f5fb9f40aa8364164729187`

2021-01-20 22:59 UTC, moosebuild commented
Job [Test](https://civet.inl.gov/job/664944/) on 1931b8a wanted to post the following:

View the site [here](https://mooseframework.inl.gov/mastodon/docs/PRs/362/site)

This comment will be updated on new commits.

2021-01-21 16:24 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/665498/) on 3ed5503 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/mastodon/docs/PRs/362/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/mastodon/docs/PRs/362/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 4d9e6a53739a071f7f5fb9f40aa8364164729187`

2021-01-25 17:52 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/667494/) on 0c95833 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/mastodon/docs/PRs/362/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/mastodon/docs/PRs/362/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 4d9e6a53739a071f7f5fb9f40aa8364164729187`

2021-01-25 18:29 UTC, somu15 commented
@cbolisetti I made changes per the discussion we had last week.

2021-01-25 22:35 UTC, cbolisetti commented
@somu15 we discussed adding more guidance on the stress direction, leverarm direction, and the direction of the resulting moment. Please add those too.

2021-02-03 19:53 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/672504/) on 8e489fa wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/mastodon/docs/PRs/362/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/mastodon/docs/PRs/362/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 4d9e6a53739a071f7f5fb9f40aa8364164729187`

2021-02-03 23:17 UTC, cbolisetti requested changes

2021-02-03 23:17 UTC, cbolisetti commented on src/postprocessors/SidesetMoment.C
> +    return ((*_p)[_qp]) * (_q_point[_qp] - _ref_point) * (*_leverarm_direction);
Is this valid only if the sideset normal is perpendicular to the leverarm direction?

2021-02-03 23:17 UTC, cbolisetti commented on src/postprocessors/SidesetMoment.C
> +  params.addParam<RealVectorValue>("stress_dir", "Stress direction");
Change to "stress_direction" to be consistent with "leverarm_direction".

2021-02-04 01:17 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/672880/) on 755ecd5 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/mastodon/docs/PRs/362/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/mastodon/docs/PRs/362/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 4d9e6a53739a071f7f5fb9f40aa8364164729187`

2021-02-04 16:43 UTC, cbolisetti requested changes

2021-02-04 16:43 UTC, cbolisetti commented on doc/content/source/postprocessors/SidesetMoment.md
> + this with the moment direction vector $(\vec{l})$ gives the scalar lever arm.
Check your math and rewrite. This is not what you are doing above.

2021-02-04 16:43 UTC, cbolisetti commented on src/postprocessors/SidesetMoment.C
> +  params.addCoupledVar("p", "The scalar pressure");
Change this to "pressure".

2021-02-11 00:36 UTC, somu15 commented
I've updated the figure, but for some reason, it's not showing the updated figure on the MOOSE test site.

2021-02-11 18:56 UTC, cbolisetti approved these changes

2021-02-11 18:56 UTC, merged